export const categories = [
    {name : "Ashish Chanchlani"},
    {name : "BB ki Vines"},
    {name : "T-series"},
    {name : "Love Babbar"},
    {name : "Priyansh Agarwal"},
    {name : "Open Source"},
    {name : "MLH FellowShip"},
    {name : "Kunal Kushwaha"},
    {name : "GSOC 2024"},
    { name: 'JS Mastery'},
    { name: 'New' },
    { name: 'Coding'},
    { name: 'ReactJS' },
    { name: 'NextJS' },
    { name: 'Music' },
    { name: 'Education' },
    { name: 'Podcast' },
    { name: 'Movie'},
    { name: 'Gaming'},
    { name: 'Live' },
    {name : "Stock Market"},
    {name: "AI"},
    {name : "Intra day Trading"},
    { name: 'Sport'},
    { name: 'Fashion' },
    { name: 'Beauty' },
    { name: 'Comedy' },
    { name: 'Gym' },
    { name: 'Crypto' },
  ];